---
ReactNativePerformanceFixture:
- "[CP] Check Pods Manifest.lock: A76540F5A50FD4CE565A2A84"
- 'Start Packager: FD10A7F022414F080027D42C'
- 'Bundle React Native code and images: 00DD1BFF1BD5951E006B06BC'
- "[CP] Copy Pods Resources: 34DDC772378489259DB67D7C"
- "[CP] Embed Pods Frameworks: C685FB23E818E68FE33CE97A"
